apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chirpstack.fullname" . }}-mosquitto
  labels:
    {{- include "chirpstack.labels" . | nindent 4 }}
    app: mosquitto
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "chirpstack.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/instance:  "mosquitto" 
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-mosquitto.yaml") . | sha256sum }}
      labels:
        {{- include "chirpstack.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/instance: "mosquitto" 
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chirpstack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.mosquitto.image.repository }}:{{ .Values.mosquitto.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
               name: {{ include "chirpstack.fullname" . }}-mosquitto
          volumeMounts:
          - name: config-volume
            mountPath: /etc/chirpstack-network-server/network-server.toml
            subPath: network-server.toml
          ports:
            - name: mosquitto
              containerPort: {{ .Values.mosquitto.service.port }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.mosquitto.service.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.mosquitto.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "chirpstack.fullname" . }}-mosquitto
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
